name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  security-events: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Build
        run: ./mvnw --batch-mode --update-snapshots verify
      - name: Codecov
        uses: codecov/codecov-action@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
